In [1]:
import numpy as np

In [2]:
my_list =[1,2,3,4]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
my_mat = [[1,2,3],[4,5,6],(6,7,8)]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
#to make a range array 
np.arange(0,10)



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#arange(start,stop,step)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
#prints a evenly spaced array of numbers from range start to stop. the third variable is how many elements you want
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
#prints an array of 5 numbers evenly spaced from 1 to 10 
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [15]:
#creates identity matrix of 4*4
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
#creates identity matrix of 3*3
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#creates an array of random numbers of 5 size 
np.random.rand(5)

array([0.02299548, 0.62984425, 0.23397466, 0.41311911, 0.06819448])

In [18]:
#creates a random array of 5*5 size
np.random.rand(5,5)

array([[0.62994174, 0.29702119, 0.3845621 , 0.73155186, 0.07639893],
       [0.1092778 , 0.44516128, 0.98639544, 0.33929903, 0.33360481],
       [0.81636524, 0.74428131, 0.28212257, 0.12596734, 0.20964051],
       [0.32700167, 0.00648314, 0.45215803, 0.28473591, 0.74340637],
       [0.44545608, 0.23352049, 0.5236871 , 0.99447208, 0.6713525 ]])

In [19]:
#creates a random integer array from low(first param) to high(next param) of a third var size
np.random.randint(1,100,10)

array([49,  8, 89, 36, 12, 14, 85, 73, 72, 48])

In [20]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
rannarr = np.random.randint(0,50,10)
rannarr

array([ 2, 13, 25, 31, 18, 17, 31, 11, 19,  7])

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
rannarr.max()

31

In [24]:
rannarr.min()

2

In [25]:
rannarr.argmax()

3

In [26]:
rannarr.argmin()

0

In [27]:
arr = arr.reshape(5,5)
print(arr)
arr.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


(5, 5)

In [28]:
arr.dtype

dtype('int32')

In [29]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr[3]

3

In [31]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [32]:
arr[2:8:2]

array([2, 4, 6])

In [33]:
 arr[:6]

array([0, 1, 2, 3, 4, 5])

In [34]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [35]:
arr[:6] = 99

In [36]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [37]:
arr = np.arange(0,10)

In [38]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
slice_of_arr = arr[6:]

In [40]:
slice_of_arr

array([6, 7, 8, 9])

In [41]:
slice_of_arr[:]

array([6, 7, 8, 9])

In [42]:
slice_of_arr

array([6, 7, 8, 9])

In [43]:
arr_2d = np.random.rand(5,5)
arr_2d

array([[0.85090041, 0.36048241, 0.35292177, 0.74795114, 0.36843261],
       [0.10383253, 0.51116569, 0.96024671, 0.72077361, 0.46619865],
       [0.93953922, 0.24703664, 0.88043661, 0.7911333 , 0.1997718 ],
       [0.68318795, 0.02682933, 0.6088731 , 0.24418124, 0.67490528],
       [0.42635367, 0.66267136, 0.20447291, 0.97868579, 0.6023597 ]])

In [44]:
arr_2d[:3,1:]

array([[0.36048241, 0.35292177, 0.74795114, 0.36843261],
       [0.51116569, 0.96024671, 0.72077361, 0.46619865],
       [0.24703664, 0.88043661, 0.7911333 , 0.1997718 ]])

In [45]:
arr_2d[2:,:3]

array([[0.93953922, 0.24703664, 0.88043661],
       [0.68318795, 0.02682933, 0.6088731 ],
       [0.42635367, 0.66267136, 0.20447291]])

In [46]:
arr_2d > 0.5

array([[ True, False, False,  True, False],
       [False,  True,  True,  True, False],
       [ True, False,  True,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True,  True]])

In [47]:
bool_arr = arr_2d > 0.5

In [48]:
bool_arr

array([[ True, False, False,  True, False],
       [False,  True,  True,  True, False],
       [ True, False,  True,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True,  True]])

In [49]:
#returns only those elements whose value > 0.5
arr_2d[bool_arr]

array([0.85090041, 0.74795114, 0.51116569, 0.96024671, 0.72077361,
       0.93953922, 0.88043661, 0.7911333 , 0.68318795, 0.6088731 ,
       0.67490528, 0.66267136, 0.97868579, 0.6023597 ])

In [50]:
arr_2d[arr_2d<0.5]

array([0.36048241, 0.35292177, 0.36843261, 0.10383253, 0.46619865,
       0.24703664, 0.1997718 , 0.02682933, 0.24418124, 0.42635367,
       0.20447291])

In [51]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
arr_2d[1:4,3:6]

array([[13, 14, 15],
       [23, 24, 25],
       [33, 34, 35]])

In [53]:
arr_2d[1:4,3:6]

array([[13, 14, 15],
       [23, 24, 25],
       [33, 34, 35]])

In [60]:
arr = np.arange(0,12)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [58]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [65]:
arr=arr.reshape(2,6)

In [66]:
arr * arr

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121]])

In [67]:
arr \ arr

SyntaxError: unexpected character after line continuation character (<ipython-input-67-e4269665f493>, line 1)

In [68]:
1 / arr

c:\users\saksh\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
        0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909]])

In [69]:
arr * 2

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22]])

In [70]:
arr ** 2

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121]], dtype=int32)

In [71]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
        3.31662479]])

In [72]:
np.exp(arr)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04, 5.98741417e+04]])

In [73]:
np.max(arr)

11

In [74]:
arr.max()

11

In [75]:
np.sin(arr)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
        -0.99999021]])

In [76]:
np.log(arr)

c:\users\saksh\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
        1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
        2.39789527]])